### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by paolobarbolini** [vansante/go-ffprobe#10]
Could you release a new version?

In particular I see this change b3d5705d7c1f063ba988824570f35b22447f3be2 where you use better names for constants to make them play nice with ``golint`` and in a comment you plan deprecate the old constants names:
https://github.com/vansante/go-ffprobe/blob/b3d5705d7c1f063ba988824570f35b22447f3be2/probedata.go#L10-L31

But since Go modules (which will be enabled by default in Go 1.13) by default install the latest git tag, that change isn't going to be available to most users who are simply going to install this using ``go get github.com/vansante/go-ffprobe`` without giving it much thought, since the commit that made that change came after the latest release, which currently is v1.0.0

**Comment by vansante** [comment]
Good point, consider it done:
https://github.com/vansante/go-ffprobe/releases/tag/v1.1.0

**Comment by paolobarbolini** [comment]
Great. Thank you.
