### ISSUE TITLE
metadata?

### ISSUE THREAD

**Issue by porjo** [vansante/go-ffprobe#35]
Could support for arbitrary stream & format tags be added by, for example, decoding [Format.Tags](https://github.com/vansante/go-ffprobe/blob/v2.0.3/probedatad.go#L32) into a `map[string]string`. My particular use case are media files with tags like `artist`, `album`, `genre` etc.

**Comment by vansante** [comment]
This is part of the new release:

https://github.com/vansante/go-ffprobe/releases/tag/v2.1.0

See: #32

**Comment by porjo** [comment]
Thanks!
