### ISSUE TITLE
Remote Files

### ISSUE THREAD

**Issue by christopheelkhoury** [vansante/go-ffprobe#9]
Is the package able to do its job for files located remotely on a server?

**Comment by vansante** [comment]
According to the [ffprobe](https://ffmpeg.org/ffprobe.html) documentation, it takes an URL, so it sounds like it could also probe remote files on accessible locations. Try it I suppose ;)

Please let me know if it works!

**Comment by christopheelkhoury** [comment]
I gave it a shot, works perfectly!
I'd hoped your package would be a wrapper without issuing OS commands. But it works like a charm. Closing the issue.
